### ISSUE TITLE
A question about TV mode

### ISSUE THREAD

**Issue by DumberSoft** [JamsRepos/Jamfin#15]
Does the theme also support TV mode?

**Comment by JamsRepos** [comment]
It should? I believe I tested it by simply turning it on my browser but I don't have a TV that uses it but give it a go and see how you manage and let me know if there's anything out the ordinary.

**Comment by DumberSoft** [comment]
But in the Jellyfin settings there is also an option in profile that can be set to TV mode so that it can be modified, however I have tested it and it is like the original, since it has other settings.

**Comment by JamsRepos** [comment]
> But in the Jellyfin settings there is also an option in profile that can be set to TV mode so that it can be modified, however I have tested it and it is like the original, since it has other settings.

Yes - that's what I tested with. The theme applies to that display mode.
