### ISSUE TITLE
Logo briefly jumps when opening any page from the home page

### ISSUE THREAD

**Issue by bravely-beep** [JamsRepos/Jamfin#17]
I enabled Jamfin CSS with all modules except `change-logo.css`, so I use the default Jellyfin logo.

On the home page, if I try to click on any item (e.g. a media library), the Jellyfin logo in the top-left corner of the screen briefly jumps to the right during the transition, before quickly vanishing. This looks ugly and distracting.

Tested on Jellyfin's native Linux client.

![image](https://github.com/user-attachments/assets/1ad5401a-2122-4b5c-9355-02f65326a9ac)

![image](https://github.com/user-attachments/assets/40a24550-4453-430a-b1e5-44b4b9f6e42b)

![image](https://github.com/user-attachments/assets/c439bd88-cdaa-4c1c-969f-a5a89f509545)

**Comment by JamsRepos** [comment]
I'm unable to replicate this on either JMP or the browser.

**Comment by bravely-beep** [comment]
Further testing shows this is happening on my machine even with the Jellyfin default CSS, so this isn't a Jamfin issue after all.
