### ISSUE TITLE
Cards do not dim when hovered

### ISSUE THREAD

**Issue by bravely-beep** [JamsRepos/Jamfin#18]
In the default Jellyfin setup, hovering the mouse over a card dims its image, allowing the overlay buttons that appear to be clearly visible no matter the color of the card image. When Jamfin is enabled, this does not occur, making the overlay buttons difficult to see on some cards.

**Comment by JamsRepos** [comment]
Thanks for your suggestion, i've added back the hover state.

**Comment by bravely-beep** [comment]
Thanks, this is great! Only issue I noticed is that on some cards, the rounded corners on the dimmed area seem to have a different radius to the rounded corners on the card image.

EDIT: examples
![image](https://github.com/user-attachments/assets/752a20e6-2646-4a6e-a155-42172e72bd57)
![image](https://github.com/user-attachments/assets/bfbd5514-ba0d-4292-89b8-fdc83e7e74ec)

**Comment by JamsRepos** [comment]
Is that with the JMP client? As I think I noticed that on there too when I was testing your other issue.

**Comment by bravely-beep** [comment]
This is with the JMP client yes
