### ISSUE TITLE
Complete Pack only includes private IPs. Causes Jellyfin to hang.

### ISSUE THREAD

**Issue by HBIDamian** [JamsRepos/Jamfin#19]
The IPs within `https://cdn.jsdelivr.net/gh/JamsRepos/Jamfin@latest/theme/complete.css` are private IP addresses. When a user attempts to use this on Jellyfin, it'll cause their client to hang until it fails to load the files.

**Comment by JamsRepos** [comment]
Seems I had missed this when working on the latest update, should be rectified now thanks!
